# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode8.2
language: objective-c
cache: cocoapods
podfile: Example/DTSImageExample/Podfile
before_install:
- gem install cocoapods # Since Travis is not always on latest version
- pod install --project-directory=Example/DTSImageExample
script:
- set -o pipefail && xcodebuild test -workspace Example/DTSImageExample/DTSImageExample.xcworkspace -scheme DTSImageExample -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6,OS=10.1' ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint
